# Generated by Django 5.2 on 2025-04-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(verbose_name=30)),
                ('ukr_word', models.CharField(verbose_name=30)),
                ('last_time_drafted', models.DateTimeField()),
                ('last_result', models.BooleanField()),
                ('is_draftable', models.BooleanField(default=True)),
            ],
        ),
    ]
